from board import CheckerBoard

checkers_board = CheckerBoard()
checkers_board.show_checker_board()
checkers_board.executeMove([[2, 0], [3, 0]])
print("\n")
checkers_board.show_checker_board()
print(checkers_board.get_moves_available())
checkers_board.executeMove([[5, 0], [4, 1]])
print("\n")
checkers_board.show_checker_board()
checkers_board.executeMove([[2, 1], [3, 1]])
print("\n")
checkers_board.show_checker_board()
print(checkers_board.get_moves_available())
checkers_board.executeMove([[5, 0], [4, 0]])
print("\n")
checkers_board.show_checker_board()
print(checkers_board.get_moves_available())