from Board import Board

checkers_board = Board()
checkers_board.print_board()
checkers_board.make_move([[2,0],[3,0]])
print("\n")
checkers_board.print_board()
print(checkers_board.get_possible_next_moves())
checkers_board.make_move([[5, 0], [4, 1]])
print("\n")
checkers_board.print_board()
checkers_board.make_move([[2, 1], [3, 1]])
print("\n")
checkers_board.print_board()
print(checkers_board.get_possible_next_moves())
checkers_board.make_move([[5, 0], [4, 0]])
print("\n")
checkers_board.print_board()
print(checkers_board.get_possible_next_moves())